version: "3.6"

services:
  smart-brain-api:
    container_name: backend
#    image: node:10.13.0
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3000:3000"
#    network_mode: none
#    networks:
#      - default
    volumes:
      - ./:/usr/src/smart-brain-api